#!/usr/bin/env python3
from pathlib import Path
import argparse, hashlib, json, math, re, sys, zlib
from collections import defaultdict
import xml.etree.ElementTree as ET

EXPECTED_ROM_SIZE = 0xC00000
EXPECTED_ROM_CRC32 = 0x434389C1
BR_ROM_CRC32 = 0x3B0D98C1
BR_ROM_SHA1 = "c2baf5b4a5355fff2dac08e971a62834ef70268c"


COURSE_ABBREVIATIONS = {
    "banshee_boardwalk": "BB",
    "big_donut": "BD",
    "block_fort": "BF",
    "bowsers_castle": "BC",
    "choco_mountain": "CM",
    "dks_jungle_parkway": "DKJ",
    "double_deck": "DD",
    "frappe_snowland": "FS",
    "kalimari_desert": "KD",
    "koopa_troopa_beach": "KTB",
    "luigi_raceway": "LR",
    "mario_raceway": "MR",
    "moo_moo_farm": "MMF",
    "rainbow_road": "RR",
    "royal_raceway": "RRW",
    "sherbet_land": "SL",
    "skyscraper": "SS",
    "toads_turnpike": "TT",
    "wario_stadium": "WS",
    "yoshi_valley": "YV",
}


def _symbol_to_asset_key(symbol):
    if not symbol.startswith("gTexture"):
        die("unexpected course texture symbol: " + symbol)
    name = symbol[len("gTexture"):]
    if re.fullmatch(r"[0-9A-F]+", name):
        return "texture_" + name
    # CamelCase -> snake_case, plus underscore before a trailing numeric suffix.
    name = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", name)
    name = re.sub(r"([A-Za-z])([0-9]+)$", r"\1_\2", name)
    name = name.lower()
    # This filename is intentionally misspelled in the upstream asset tree.
    if name == "checkerboard_yellow_blue":
        name = "checkerbord_yellow_blue"
    return name


def generate_course_linkonly(root, recipes):
    """Regenerate the 20 course_textures.linkonly.c/.h pairs required by MK64.vcxproj."""
    recipe_paths = {str(r["path"]).replace("\\", "/") for r in recipes}
    standalone = {}
    for rel in recipe_paths:
        if not rel.startswith("textures/standalone/"):
            continue
        base = Path(rel).name
        key = base.split(".", 1)[0]
        standalone.setdefault(key, []).append(rel)

    texture_re = re.compile(r"{\s*(\S+),\s+\S+,\s+(\S+),\s+\S+\s*}")
    generated = 0

    for course_name, abbrev in COURSE_ABBREVIATIONS.items():
        course_dir = root / "courses" / course_name
        offsets = course_dir / "course_offsets.c"
        if not offsets.is_file():
            die("missing course offsets required for linkonly generation: " + str(offsets))

        entries = texture_re.findall(offsets.read_text(encoding="utf-8", errors="strict"))
        if not entries:
            die("failed to find texture entries in " + str(offsets))

        h_lines = [
            "#ifndef COURSE_TEXTURES_H",
            "#define COURSE_TEXTURES_H",
            "",
            "#include <PR/ultratypes.h>",
        ]
        c_lines = [f'#include "courses/{course_name}/course_textures.linkonly.h"']

        current_offset = 0
        used = 0
        for symbol, size_text in entries:
            if symbol == "0x00000000":
                continue

            try:
                size = int(size_text, 0)
            except ValueError:
                die(f"invalid texture size {size_text!r} in {offsets}")

            if "MooMooFarm" in symbol:
                include_rel = f"assets/courses/moo_moo_farm/{symbol}.inc.c"
                if include_rel not in recipe_paths:
                    die("no public asset recipe for course texture: " + include_rel)
            else:
                key = _symbol_to_asset_key(symbol)
                matches = standalone.get(key, [])
                if len(matches) != 1:
                    die(
                        f"could not uniquely map {symbol} in {course_name} to a public asset recipe "
                        f"(key={key!r}, matches={matches})"
                    )
                include_rel = matches[0]

            unique_symbol = re.sub(r"^gTexture", f"g{abbrev}Texture", symbol)

            c_lines += [
                "",
                f"/* 0x050{current_offset:05X} */",
                f"u8 {unique_symbol}[] = {{",
                f'\t#include "{include_rel}"',
                "};",
            ]
            h_lines += [
                "",
                f"/* 0x050{current_offset:05X} */",
                f"extern u8 {unique_symbol}[];",
            ]
            current_offset += size
            used += 1

        h_lines += ["", "#endif", ""]
        c_lines += [""]

        (course_dir / "course_textures.linkonly.h").write_text(
            "\n".join(h_lines), encoding="utf-8", newline="\n"
        )
        (course_dir / "course_textures.linkonly.c").write_text(
            "\n".join(c_lines), encoding="utf-8", newline="\n"
        )
        generated += 1

        # Every include emitted into linkonly.c must have been regenerated by the
        # public asset recipes before the Xbox project is allowed to build.
        for rel in re.findall(r'#include\s+"([^"]+\.inc\.c)"',
                              (course_dir / "course_textures.linkonly.c").read_text(encoding="utf-8")):
            if not (root / rel).is_file():
                die(f"generated {course_name}/course_textures.linkonly.c references missing asset: {rel}")

        if used == 0:
            die("generated empty linkonly source for " + course_name)

    return generated


def verify_linkonly_dependencies(root):
    missing = []
    for course_name in COURSE_ABBREVIATIONS:
        course_dir = root / "courses" / course_name
        for name in ("course_textures.linkonly.h", "course_textures.linkonly.c"):
            p = course_dir / name
            if not p.is_file():
                missing.append(str(p.relative_to(root)))
    if missing:
        die("course linkonly generation is incomplete:\n  " + "\n  ".join(missing))


def die(msg):
    raise SystemExit("ERROR: " + msg)


def sha256(data):
    return hashlib.sha256(data).hexdigest()


def mio0_decode(src):
    if len(src) < 16 or src[:4] != b"MIO0":
        raise ValueError("not MIO0")
    out_size = int.from_bytes(src[4:8], "big")
    comp_pos = int.from_bytes(src[8:12], "big")
    raw_pos = int.from_bytes(src[12:16], "big")
    ctrl_pos = 16
    out = bytearray()
    mask = 0
    ctrl = 0
    while len(out) < out_size:
        if mask == 0:
            if ctrl_pos >= len(src): raise ValueError("truncated MIO0 control stream")
            ctrl = src[ctrl_pos]; ctrl_pos += 1; mask = 0x80
        if ctrl & mask:
            if raw_pos >= len(src): raise ValueError("truncated MIO0 raw stream")
            out.append(src[raw_pos]); raw_pos += 1
        else:
            if comp_pos + 2 > len(src): raise ValueError("truncated MIO0 backref stream")
            pair = (src[comp_pos] << 8) | src[comp_pos + 1]; comp_pos += 2
            length = (pair >> 12) + 3
            distance = (pair & 0x0FFF) + 1
            if distance > len(out): raise ValueError("invalid MIO0 back-reference")
            for _ in range(length):
                out.append(out[-distance])
                if len(out) >= out_size: break
        mask >>= 1
    return bytes(out)


def source_bytes(rom, rom_offset, cache):
    if rom_offset in cache: return cache[rom_offset]
    if rom_offset < 0 or rom_offset >= len(rom):
        die(f"ROM offset out of range: 0x{rom_offset:X}")
    if rom[rom_offset:rom_offset+4] == b"MIO0":
        try: data = mio0_decode(rom[rom_offset:])
        except Exception as e: die(f"MIO0 decode failed at 0x{rom_offset:X}: {e}")
    else:
        data = rom[rom_offset:]
    cache[rom_offset] = data
    return data


def format_u8(data):
    vals=[f"0x{b:02x}" for b in data]
    return "\n".join(",".join(vals[i:i+24])+"," for i in range(0,len(vals),24)) + "\n"


def format_u16be(data):
    if len(data)%2: die("u16 payload has odd byte length")
    vals=[f"0x{int.from_bytes(data[i:i+2],'big'):04x}" for i in range(0,len(data),2)]
    return "\n".join(", ".join(vals[i:i+8])+"," for i in range(0,len(vals),8)) + "\n"


def format_struct4(data):
    if len(data)%4: die("staff-ghost payload is not divisible by 4")
    rows=[]
    for i in range(0,len(data),4):
        a,b,c,d=data[i:i+4]
        rows.append(f"{{ 0x{a:02X}, {b}, {c}, {d} }}")
    return "\n".join("    "+", ".join(rows[i:i+5])+"," for i in range(0,len(rows),5)) + "\n"


def payload_from_text(text, representation):
    vals=[int(x,0) for x in re.findall(r"0[xX][0-9A-Fa-f]+|\b\d+\b",text)]
    if representation == "u16be":
        if any(v>0xFFFF for v in vals): die("generated u16 initializer contains out-of-range value")
        return b"".join(v.to_bytes(2,"big") for v in vals)
    if any(v>255 for v in vals): die("generated byte initializer contains out-of-range value")
    return bytes(vals)


def verify_gold_source(root, hashes):
    bad=[]
    for rel,expected in hashes.items():
        p=root/rel
        if not p.is_file():
            bad.append(f"missing {rel}")
            continue

        data=p.read_bytes()
        got=sha256(data)
        if got==expected:
            continue

        # Git on Windows may check .cpp/text files out as CRLF even when the
        # public gold hashes were recorded from LF source.  Line-ending style
        # is not a source-code change, so retry using canonical LF bytes.
        canonical=data.replace(b"\r\n",b"\n").replace(b"\r",b"\n")
        canonical_hash=sha256(canonical)
        if canonical_hash==expected:
            continue

        bad.append(f"changed {rel}: {got}")

    if bad:
        die("working 2-player gold source was changed. Refusing to prepare assets:\n  " + "\n  ".join(bad))


def verify_project(root):
    project = root.parent / 'MK64' / 'MK64.vcxproj'
    if not project.is_file():
        print("NOTE: MK64.vcxproj was not found next to mk64-master; project dependency check skipped.")
        return

    ns = 'http://schemas.microsoft.com/developer/msbuild/2003'
    tree = ET.parse(project)
    compile_files = []
    missing_compile = []
    for n in tree.getroot().iter('{%s}ClCompile' % ns):
        inc = n.attrib.get('Include', '')
        if not inc:
            continue
        rel = inc.replace('\\', '/')
        if rel.startswith('../mk64-master/'):
            p = root / rel[len('../mk64-master/'):]
            if p.is_file():
                compile_files.append(p.resolve())
            else:
                missing_compile.append(rel)

    if missing_compile:
        die("project still has missing C/C++ compile inputs after preparation:\n  " +
            "\n  ".join(missing_compile[:100]))

    # The Visual Studio project has a fixed set of local include roots. Walk all
    # project translation units recursively so missing generated .inc.c/.h files
    # are caught here instead of much later by MSBuild.
    include_dirs = [
        root,
        root / 'include',
        root / 'src',
        root / 'src' / 'racing',
        root / 'src' / 'ending',
        root / 'src' / 'audio',
        root / 'src' / 'data',
        root / 'courses',
    ]
    include_re = re.compile(r'^\s*#\s*include\s*[<\"]([^>\"]+)[>\"]', re.M)
    local_prefixes = (
        'assets/', 'courses/', 'textures/', 'src/', 'data/', 'xbox360/',
        'PR/', 'ultra64.h', 'macros.h', 'defines.h', 'types.h', 'config.h'
    )

    seen = set()
    queue = list(compile_files)
    missing_local = set()

    while queue:
        src = queue.pop()
        if src in seen or not src.is_file():
            continue
        seen.add(src)
        try:
            text = src.read_text(encoding='utf-8', errors='ignore')
        except OSError:
            continue

        for name in include_re.findall(text):
            name = name.replace('\\', '/')
            candidates = [src.parent / name] + [d / name for d in include_dirs]
            resolved = next((p.resolve() for p in candidates if p.is_file()), None)
            if resolved is not None:
                try:
                    resolved.relative_to(root.resolve())
                except ValueError:
                    continue
                # Recurse into local source/header/include fragments.
                if resolved.suffix.lower() in ('.c', '.h', '.hpp', '.inl') or resolved.name.endswith('.inc.c'):
                    queue.append(resolved)
                continue

            # Ignore XDK/system headers, but require all paths that clearly refer
            # to this source tree or to generated include fragments.
            is_local = name.endswith('.inc.c') or name.endswith('.linkonly.h') or name.startswith(local_prefixes)
            if is_local:
                try:
                    relsrc = str(src.relative_to(root)).replace('\\', '/')
                except ValueError:
                    relsrc = str(src)
                missing_local.add(f"{name}  (included by {relsrc})")

    if missing_local:
        die("project still has missing local include dependencies after preparation:\n  " +
            "\n  ".join(sorted(missing_local)[:100]))


def main():
    ap=argparse.ArgumentParser(description="Regenerate excluded MK64 media payload source from the selected ROM variant without changing runtime source layout.")
    ap.add_argument('--root', help='mk64-master directory (defaults to directory containing this script)')
    ap.add_argument('--rom', help='ROM path (defaults to mk64-master/baserom.br.z64)')
    args=ap.parse_args()
    root=Path(args.root).expanduser().resolve() if args.root else Path(__file__).resolve().parent
    recipes_path=root/'PUBLIC_ASSET_RECIPES.json'
    banks_path=root/'PUBLIC_GENERATED_BANK_MAP.json'
    hashes_path=root/'PUBLIC_SOURCE_GOLD_HASHES.json'
    for p in (recipes_path,banks_path,hashes_path):
        if not p.is_file(): die("missing public preparation metadata: "+str(p))
    recipes=json.loads(recipes_path.read_text(encoding='utf-8'))
    banks=json.loads(banks_path.read_text(encoding='utf-8'))
    gold=json.loads(hashes_path.read_text(encoding='utf-8'))
    verify_gold_source(root,gold)

    rom_path=Path(args.rom).expanduser().resolve() if args.rom else root/'baserom.br.z64'
    if not rom_path.is_file():
        die("baserom.br.z64 not found. Put your BR ROM at:\n  "+str(root/'baserom.br.z64')+"\nor pass --rom <path>.")
    rom=rom_path.read_bytes()
    if len(rom)!=EXPECTED_ROM_SIZE: die(f"ROM size mismatch: got 0x{len(rom):X}, expected 0x{EXPECTED_ROM_SIZE:X}")
    crc=zlib.crc32(rom)&0xFFFFFFFF
    got_sha1=hashlib.sha1(rom).hexdigest()
    is_br_variant = (crc == BR_ROM_CRC32 and got_sha1 == BR_ROM_SHA1)
    if crc != EXPECTED_ROM_CRC32 and not is_br_variant:
        die(f"ROM CRC32 mismatch: got {crc:08X}, expected {EXPECTED_ROM_CRC32:08X} (USA) or {BR_ROM_CRC32:08X} (BR)")
    sha_file=root/'mk64.us.sha1'
    if sha_file.is_file() and not is_br_variant:
        expected=sha_file.read_text(encoding='utf-8',errors='ignore').split()[0].lower()
        if expected and got_sha1!=expected: die(f"ROM SHA1 mismatch: got {got_sha1}, expected {expected}")

    print("MK64 public-source asset preparation")
    print("="*72)
    print("Source:",root)
    print("ROM:   ",rom_path)
    if is_br_variant:
        print(f"ROM CRC32: {crc:08X} [BR variant accepted]")
        print(f"ROM SHA1:  {got_sha1} [BR variant accepted]")
    else:
        print(f"ROM CRC32: {crc:08X} [OK]")
    print(f"Media fragments to regenerate: {len(recipes)}")
    print(f"Generated-bank objects:         {len(banks)}")
    print()

    cache={}
    generated=0
    # First extract and verify every media fragment in memory so a bad recipe
    # cannot leave a half-generated source tree.
    pending=[]
    for i,r in enumerate(recipes,1):
        src=source_bytes(rom,int(r['rom_offset']),cache)
        off=int(r.get('block_offset',0)); size=int(r['size'])
        if off<0 or off+size>len(src): die(f"asset range outside source block: {r['path']}")
        data=src[off:off+size]
        got=sha256(data)
        if got!=r['sha256'] and not is_br_variant:
            die("asset verification mismatch before writing:\n"
                f"  {r['path']}\n  ROM/source 0x{int(r['rom_offset']):X}+0x{off:X}\n"
                f"  expected {r['sha256']}\n  got      {got}\n"
                "This recipe deliberately stops instead of generating source with different bytes.")
        rep=r['representation']
        if rep=='u8': text=format_u8(data)
        elif rep=='u16be': text=format_u16be(data)
        elif rep=='struct4': text=format_struct4(data)
        else: die("unknown representation: "+rep)
        # Round-trip our emitted source before touching disk.
        if sha256(payload_from_text(text,rep))!=r['sha256'] and not is_br_variant:
            die("internal source-format roundtrip failed for "+r['path'])
        pending.append((root/r['path'],text,r))

    # Verify all generated banks directly against the ROM before writing any.
    grouped=defaultdict(list)
    for r in banks:
        off=int(r['rom_offset']); size=int(r['size'])
        if off<0 or off+size>len(rom): die(f"generated-bank range outside ROM: {r['symbol']}")
        data=rom[off:off+size]
        if sha256(data)!=r['sha256'] and not is_br_variant:
            die(f"generated-bank verification mismatch: {r['bank']} / {r['symbol']}")
        grouped[r['bank']].append((r,data))

    # All verification passed: write media fragments.
    for p,text,r in pending:
        p.parent.mkdir(parents=True,exist_ok=True)
        p.write_text(text,encoding='utf-8',newline='\n')
        generated+=1

    # Write the 13 bank translation units with the same symbol ordering,
    # alignment and initialized-array semantics as the working gold build.
    bank_dir=root/'src'/'xbox360'/'generated_banks'
    bank_dir.mkdir(parents=True,exist_ok=True)
    for bank,items in grouped.items():
        lines=["/* Generated locally from the user's verified selected ROM variant. */"]
        for r,data in items:
            lines.append(f"__declspec(align(16)) unsigned char {r['symbol']}[] = {{")
            vals=[f"0x{b:02X}" for b in data]
            lines += [",".join(vals[i:i+24])+"," for i in range(0,len(vals),24)]
            lines.append("};")
        (bank_dir/bank).write_text("\n".join(lines)+"\n",encoding='utf-8',newline='\n')

    # The upstream build normally generates course_textures.linkonly.c/.h with
    # tools/linkonly_generator.py. The public Xbox source intentionally does not
    # ship the full tools tree, so regenerate those helper files here from
    # course_offsets.c plus the verified public asset recipes.
    linkonly_count = generate_course_linkonly(root, recipes)
    verify_linkonly_dependencies(root)

    # Re-open every generated media source and prove it still normalizes to
    # the exact expected bytes.
    for p,_,r in pending:
        got=sha256(payload_from_text(p.read_text(encoding='utf-8'),r['representation']))
        if got!=r['sha256'] and not is_br_variant: die("post-write media verification failed: "+r['path'])

    # Re-open every bank and check declaration count/order. Byte hashes were
    # already checked against the ROM before writing.
    arr_re=re.compile(r'__declspec\s*\(\s*align\s*\(\s*16\s*\)\s*\)\s*unsigned\s+char\s+([A-Za-z_]\w*)\s*\[\s*\]\s*=\s*\{(.*?)\};',re.S)
    hex_re=re.compile(r'0x([0-9A-Fa-f]{2})')
    for bank,items in grouped.items():
        text=(bank_dir/bank).read_text(encoding='utf-8')
        parsed=arr_re.findall(text)
        if len(parsed)!=len(items): die(f"post-write bank object count mismatch: {bank}")
        for (sym,body),(r,data) in zip(parsed,items):
            if sym!=r['symbol']: die(f"post-write bank symbol order mismatch: {bank}")
            b=bytes(int(x,16) for x in hex_re.findall(body))
            if sha256(b)!=r['sha256'] and not is_br_variant: die(f"post-write bank bytes mismatch: {bank}/{sym}")

    verify_project(root)
    marker=root/'PUBLIC_ASSETS_PREPARED.txt'
    marker.write_text(
        "MK64 Xbox 360 public source assets regenerated from the selected ROM variant.\n"
        f"Media fragments: {len(recipes)}\nGenerated bank objects: {len(banks)}\n"
        f"ROM CRC32: {crc:08X}\n",
        encoding='utf-8')
    print()
    print("SUCCESS")
    print(f"  regenerated {len(recipes)} excluded media source fragments")
    print(f"  regenerated {len(grouped)} generated-bank C files / {len(banks)} objects")
    print(f"  regenerated {linkonly_count} course linkonly C/header pairs")
    print("  gold runtime/netplay source was not modified")
    if is_br_variant:
        print("  BR-specific ROM bytes were used for ROM-derived assets; USA audit hashes were bypassed for those assets")
    else:
        print("  all extracted bytes matched the audited working-source hashes")
    print()
    print("You can now build MK64.sln in Xbox 360 Release configuration.")

if __name__=='__main__': main()
